### PR TITLE
Bump runtime to 44

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
> Build [13655 failed](https://buildbot.flathub.org/#/builders/6/builds/13655)

Needs 22.08 of SDK extension https://github.com/flathub/org.freedesktop.Sdk.Extension.dmd/issues/17

**Comment by hfiguiere** [comment]
bot, build

**Comment by bbhtt** [comment]
> bot, build

Thank you!

**Comment by bbhtt** [comment]
cc @kendellfab

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Seems to launch, merging as maintainer is inactive.

**Pull request merged**
